### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by gld1982ltd** [vera-desktop/vera-plugin-power#2]
``` shell
[Entering directory src]
Unable to compile library power:
 - Unable to find Vala package upower-glib
[Build failed]
```

**Comment by g7** [comment]
Hello,

upower-glib is available in the vapis/ directory. This issue is similar to the issue you have with the vera core.
To workaround, you may try to copy the upower-glib vapi in /usr/share/vala/vapi.

Eugenio

**Comment by g7** [comment]
1835f9e fixes this. Now the .gir files is directly used instead of the manually generated vapi we previously had.

A bug in bake doesn't make the plugin to compile though (with a similar issue as in your OP).

You must patch bake with [this patch](https://github.com/semplice/bake/commit/b1fdbdf6377c200923e672e228fb11f40f31c47a.patch) to get rid of the issue.

Eugenio
