### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by gld1982ltd** [vera-desktop/vera-plugin-power#3]
[Entering directory src]
Unable to compile library power:
- Unable to find Vala package UPowerGlib-1.0
  [Build failed]

**Comment by g7** [comment]
Hello,

as said in #2, you need [this patch](https://github.com/semplice/bake/commit/b1fdbdf6377c200923e672e228fb11f40f31c47a.patch) to apply on bake in order to properly compile the power plugin.

Please note that the "semplice" branch on that bake repository does NOT contain the patched sources. As our bake version is still not a fork but only a downstream-patched version, the source is upstream's and - to be compilant with the Debian policy - our changes are applied via patches.

The changes in the patch linked above are in the "gir_lookup" branch. You may merge it during build.

Eugenio
